# -*- coding: utf-8 -*-
"""Untitled3.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1mqBo70q6hCfPFfRlftOw6WyaOf6nqXbn
"""

#!/usr/bin/env python3
"""
Hyderabad Pharma Company Enrichment Tool
=========================================
Reads the input XLSX (header row 1, data from row 2),
scrapes each company website + DuckDuckGo search,
calls Gemini API for structured analysis, and writes an
enriched colour-coded XLSX.

FIXES v3:
  1. Updated model list to current 2025 models (gemini-2.5-flash, gemini-2.5-pro, etc.)
  2. On 429, waits 65 seconds and retries instead of failing
  3. On probe failure, calls ListModels to show EXACTLY what your key can access
  4. API key check improved — warns on AQ. prefix but doesn't block execution
  5. Gemini 1.5 models removed (blocked for new projects since April 2025)
"""

import sys, os, re, time, json, traceback
import requests
import pandas as pd
from bs4 import BeautifulSoup
from urllib.parse import urljoin, quote

# ── !! SET YOUR API KEY HERE !! ───────────────────────────────────────────────
# Get a FREE key (no credit card) at: https://aistudio.google.com/app/apikey
# The key MUST start with "AIza..." — anything else is wrong.
GEMINI_API_KEY = "AQ.Ab8RN6LfsknEDq2QlfU-A6lB2BXcmkMkCJADy4bgtm92Hd2RYA"

# ── Gemini model priority list ────────────────────────────────────────────────
# Script will try each in order and use the first that works.
# Current stable free-tier models as of May 2025:
GEMINI_MODELS = [
    "gemini-2.5-flash-preview-05-20",   # latest 2.5 Flash (free tier)
    "gemini-2.5-flash",                  # stable alias
    "gemini-2.5-pro-preview-05-06",      # 2.5 Pro (limited free tier)
    "gemini-2.0-flash",                  # 2.0 Flash fallback
    "gemini-2.0-flash-lite",             # lightest / fastest
]

# ── Config ────────────────────────────────────────────────────────────────────
INPUT_FILE  = "/content/Hyderabad_Pharma_Companies (1).xlsx"
OUTPUT_FILE = "/content/Hyderabad_Pharma_Enriched.xlsx"

SCRAPE_HEADERS = {
    "User-Agent": (
        "Mozilla/5.0 (Windows NT 10.0; Win64; x64) "
        "AppleWebKit/537.36 (KHTML, like Gecko) "
        "Chrome/124.0.0.0 Safari/537.36"
    ),
    "Accept": "text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8",
    "Accept-Language": "en-US,en;q=0.9",
    "Connection": "keep-alive",
}
TIMEOUT    = 20
PAUSE      = 3.0   # seconds between companies (helps stay under rate limits)
MAX_TEXT   = 5000
MAX_SEARCH = 2000

# ── Scoring prompt ─────────────────────────────────────────────────────────────
SCORING_PROMPT_TEMPLATE = """\
You are a B2B sales intelligence analyst evaluating Indian pharma / life-sciences companies.
Return ONLY valid JSON — no markdown fences, no preamble, no trailing text.

Required keys (exact spelling):
{
  "Decision Maker": "Full name of top decision-maker (MD / CMD / Founder / CEO). Write 'Unknown' if not found.",
  "DM Title": "Title / role of that person",
  "DM Background": "2-sentence background covering education and career",
  "C1 Manufacturer Score": "Strong | Moderate | Weak",
  "C1 Evidence": "1 sentence of supporting evidence",
  "C2 India Score": "Strong | Moderate | Weak",
  "C2 Evidence": "1 sentence of supporting evidence",
  "C3 Differentiation Score": "Strong | Moderate | Weak",
  "C3 Evidence": "1 sentence of supporting evidence",
  "C4 Tech DM Score": "Strong | Moderate | Weak",
  "C4 Evidence": "1 sentence of supporting evidence",
  "C5 Tailwind Score": "Strong | Moderate | Weak",
  "C5 Evidence": "1 sentence of supporting evidence",
  "C6 Growth Score": "Strong | Moderate | Weak",
  "C6 Evidence": "1 sentence of supporting evidence",
  "Federer Score": 0,
  "Score Band": "A — Strong Federer | B — Moderate Federer | C — Weak Federer | D — Not Federer",
  "Verdict": "Strong Pass | Pass | Weak Pass | Fail",
  "Verdict Reasoning": "2-3 sentences explaining the verdict",
  "Personalization Hook": "1 punchy sentence usable as a cold-email opener referencing something specific about this company",
  "Evidence Sources": "comma-separated list of URLs or named sources consulted"
}

Scoring criteria:
  C1 Manufacturer Score    — Does the company actually manufacture (not just trade/distribute)?
  C2 India Score           — Is HQ and primary operations in India (Hyderabad preferred)?
  C3 Differentiation Score — Proprietary products, patents, regulated-market approvals?
  C4 Tech DM Score         — Is the decision-maker technically trained (PhD/MTech/pharmacist)?
  C5 Tailwind Score        — Riding high-growth sector (PLI, USFDA generics, biosimilars, API China+1)?
  C6 Growth Score          — Evidence of revenue growth, new facilities, USFDA approvals in last 2 years?

Federer Score: Strong=17, Moderate=9, Weak=3 per criterion. Sum, cap at 100.
Score Band: 85-100=A Strong Federer, 60-84=B Moderate, 35-59=C Weak, 0-34=D Not Federer
Verdict: A=Strong Pass, B=Pass, C=Weak Pass, D=Fail

Company context:
  Name    : __NAME__
  Website : __WEBSITE__
  City    : __CITY__
  Segment : __SEGMENT__
  Products: __PRODUCTS__
  Revenue : __REVENUE__

Scraped website text (truncated):
__TEXT__

Web search snippet:
__SEARCH__
"""

NEW_COLS = [
    "Decision Maker", "DM Title", "DM Background",
    "C1 Manufacturer Score", "C1 Evidence",
    "C2 India Score",         "C2 Evidence",
    "C3 Differentiation Score", "C3 Evidence",
    "C4 Tech DM Score",       "C4 Evidence",
    "C5 Tailwind Score",      "C5 Evidence",
    "C6 Growth Score",        "C6 Evidence",
    "Federer Score", "Score Band", "Verdict", "Verdict Reasoning",
    "Personalization Hook", "Evidence Sources",
]
EMPTY_ROW = {c: "" for c in NEW_COLS}

# ── Helpers ───────────────────────────────────────────────────────────────────

def clean_url(url):
    url = url.strip()
    if not url.startswith("http"):
        url = "https://" + url
    return url

def extract_text(html):
    try:
        soup = BeautifulSoup(html, "lxml")
    except Exception:
        soup = BeautifulSoup(html, "html.parser")
    for tag in soup(["script","style","nav","footer","header","noscript","svg","iframe"]):
        tag.decompose()
    return " ".join(soup.stripped_strings)

def safe_get(url, session):
    for _ in range(2):
        try:
            r = session.get(url, headers=SCRAPE_HEADERS, timeout=TIMEOUT, allow_redirects=True)
            if r.status_code == 200:
                return r
        except requests.exceptions.SSLError:
            try:
                r = session.get(url.replace("https://","http://"), headers=SCRAPE_HEADERS,
                                timeout=TIMEOUT, allow_redirects=True)
                if r.status_code == 200:
                    return r
            except Exception:
                pass
        except Exception:
            pass
        time.sleep(1)
    return None

def scrape_website(url):
    sources, text = [], ""
    if not url or url.lower() in ("nan","none",""):
        return "", []
    session = requests.Session()
    base = clean_url(url)
    sources.append(base)
    r = safe_get(base, session)
    if r:
        text = extract_text(r.text)
    for slug in ("/about-us","/about","/company","/who-we-are","/leadership"):
        try:
            r2 = safe_get(urljoin(base, slug), session)
            if r2 and "text/html" in r2.headers.get("content-type",""):
                extra = extract_text(r2.text)
                if len(extra) > 300:
                    text += " " + extra
                    sources.append(urljoin(base, slug))
                    break
        except Exception:
            continue
    return text[:MAX_TEXT], sources

def duckduckgo_search(query):
    try:
        url = "https://html.duckduckgo.com/html/?q=" + quote(query)
        r = requests.get(url, headers=SCRAPE_HEADERS, timeout=TIMEOUT)
        soup = BeautifulSoup(r.text, "lxml")
        snippets = [el.get_text(" ", strip=True) for el in soup.select(".result__snippet")[:6]]
        if not snippets:
            snippets = [el.get_text(" ", strip=True)
                        for el in soup.select("[data-result='snippet']")[:6]]
        return " | ".join(snippets)[:MAX_SEARCH]
    except Exception as e:
        return f"[search failed: {e}]"

def build_prompt(name, website, city, segment, products, revenue, text, search):
    p = SCORING_PROMPT_TEMPLATE
    for k, v in [("__NAME__",name),("__WEBSITE__",website),("__CITY__",city),
                 ("__SEGMENT__",segment),("__PRODUCTS__",products),("__REVENUE__",revenue),
                 ("__TEXT__",text),("__SEARCH__",search)]:
        p = p.replace(k, str(v))
    return p

# ── Gemini API caller ─────────────────────────────────────────────────────────

_working_model = None

def list_available_models():
    """Call ListModels to show what this API key can actually access."""
    url = f"https://generativelanguage.googleapis.com/v1beta/models?key={GEMINI_API_KEY}"
    try:
        r = requests.get(url, timeout=15)
        if r.ok:
            models = r.json().get("models", [])
            names = [m["name"].replace("models/","") for m in models
                     if "generateContent" in m.get("supportedGenerationMethods", [])]
            print(f"\n  📋 Models available on your key that support generateContent:")
            for n in names:
                print(f"     • {n}")
            return names
        else:
            print(f"  !! ListModels failed: {r.status_code} {r.text[:200]}")
    except Exception as e:
        print(f"  !! ListModels error: {e}")
    return []

def get_working_model():
    global _working_model
    if _working_model:
        return _working_model

    test_payload = {
        "contents": [{"parts": [{"text": "Say OK"}]}],
        "generationConfig": {"maxOutputTokens": 5},
    }

    for model in GEMINI_MODELS:
        url = (f"https://generativelanguage.googleapis.com/v1beta/models/"
               f"{model}:generateContent?key={GEMINI_API_KEY}")
        try:
            r = requests.post(url, json=test_payload, timeout=20)
            if r.ok:
                print(f"  ✅ Using Gemini model: {model}")
                _working_model = model
                return model
            elif r.status_code == 429:
                print(f"  ⏳ {model}: rate limited (429) — waiting 65s …")
                time.sleep(65)
                # retry once after wait
                r2 = requests.post(url, json=test_payload, timeout=20)
                if r2.ok:
                    print(f"  ✅ Using Gemini model: {model} (after wait)")
                    _working_model = model
                    return model
                else:
                    print(f"  ✗  {model}: still {r2.status_code} after wait")
            else:
                print(f"  ✗  {model}: HTTP {r.status_code}")
        except Exception as e:
            print(f"  ✗  {model}: {e}")

    # Nothing worked — show diagnostic
    print("\n  ❌ No working model found. Fetching what your key CAN access …")
    available = list_available_models()
    if available:
        print(f"\n  ➡  Add one of these to GEMINI_MODELS at the top of the script and re-run.")
    raise RuntimeError(
        "\nNo working Gemini model found.\n"
        "Most likely cause: your API key is wrong or expired.\n"
        "→ Get a fresh key at: https://aistudio.google.com/app/apikey\n"
        "→ The key MUST start with 'AIza...'\n"
        "→ Paste it into GEMINI_API_KEY at the top of this script."
    )


def call_gemini(prompt, retry=True):
    model = get_working_model()
    url = (f"https://generativelanguage.googleapis.com/v1beta/models/"
           f"{model}:generateContent?key={GEMINI_API_KEY}")
    payload = {
        "contents": [{"parts": [{"text": prompt}]}],
        "generationConfig": {"temperature": 0.1, "maxOutputTokens": 4000},
    }
    r = requests.post(url, json=payload, timeout=90)

    if r.status_code == 429 and retry:
        print(f"    ⏳ Rate limited — waiting 65s …")
        time.sleep(65)
        return call_gemini(prompt, retry=False)

    if not r.ok:
        try:
            err = r.json()
            print(f"\n    !! Gemini {r.status_code}: {json.dumps(err, indent=2)}")
        except Exception:
            print(f"\n    !! Gemini {r.status_code}: {r.text[:300]}")
        r.raise_for_status()

    resp = r.json()
    candidates = resp.get("candidates", [])
    if not candidates:
        raise ValueError(f"No candidates returned: {resp}")
    if candidates[0].get("finishReason") == "SAFETY":
        raise ValueError("Blocked by safety filters")

    raw = candidates[0]["content"]["parts"][0]["text"].strip()
    raw = re.sub(r"^```(?:json)?\s*", "", raw)
    raw = re.sub(r"\s*```$", "", raw)
    try:
        return json.loads(raw)
    except json.JSONDecodeError:
        # Gemini truncated mid-string — find the last complete key-value pair and close the object
        last_comma = raw.rfind('",\n')
        if last_comma == -1:
            last_comma = raw.rfind('",')
        if last_comma != -1:
            repaired = raw[: last_comma + 1] + "\n}"
            try:
                return json.loads(repaired)
            except json.JSONDecodeError:
                pass
        raise


def enrich_row(row):
    name     = str(row.get("Company Name", "")).strip()
    website  = str(row.get("Website", "")).strip()
    segment  = str(row.get("Segment", "")).strip()
    products = str(row.get("What They Make", "")).strip()
    revenue  = str(row.get("Revenue Band", "")).strip()
    city     = str(row.get("City", "Hyderabad")).strip()

    if not name or name.lower() in ("nan",""):
        return EMPTY_ROW.copy()

    print(f"    Scraping  {website or '(no website)'} …")
    page_text, sources = (scrape_website(website)
                          if website and website.lower() not in ("nan","none","")
                          else ("", []))
    if not page_text:
        print(f"    [WARN] No text scraped — relying on search only")

    query = f"{name} Hyderabad pharma CEO founder revenue growth USFDA"
    print(f"    Searching '{query[:65]}…'")
    search_snip = duckduckgo_search(query)

    prompt = build_prompt(name, website, city, segment, products, revenue,
                          page_text, search_snip)
    print(f"    Analysing with Gemini …")
    try:
        result = call_gemini(prompt)
        src_field = result.get("Evidence Sources", "")
        all_srcs  = sources + [s.strip() for s in src_field.split(",") if s.strip()]
        seen, deduped = set(), []
        for s in all_srcs:
            if s not in seen:
                seen.add(s); deduped.append(s)
        result["Evidence Sources"] = "; ".join(deduped)
        return {c: result.get(c, "") for c in NEW_COLS}
    except Exception as e:
        print(f"    [ERROR] {e}")
        traceback.print_exc()
        row_err = EMPTY_ROW.copy()
        row_err["Verdict"]           = "Error"
        row_err["Verdict Reasoning"] = str(e)
        return row_err


# ── XLSX styling ──────────────────────────────────────────────────────────────

def style_workbook(output_path, orig_col_count, all_col_names):
    from openpyxl import load_workbook
    from openpyxl.styles import Font, PatternFill, Alignment, Border, Side
    from openpyxl.utils import get_column_letter

    wb = load_workbook(output_path)
    ws = wb.active
    thin   = Side(border_style="thin", color="D9D9D9")
    border = Border(left=thin, right=thin, top=thin, bottom=thin)
    orig_fill = PatternFill("solid", fgColor="1F3864")
    new_fill  = PatternFill("solid", fgColor="2E75B6")
    hdr_font  = Font(bold=True, color="FFFFFF", size=10, name="Arial")

    verdict_fill = {
        "Strong Pass": PatternFill("solid", fgColor="C6EFCE"),
        "Pass":        PatternFill("solid", fgColor="FFEB9C"),
        "Weak Pass":   PatternFill("solid", fgColor="FFCC99"),
        "Fail":        PatternFill("solid", fgColor="FFC7CE"),
        "Error":       PatternFill("solid", fgColor="E0E0E0"),
    }
    band_fill = {
        "A — Strong Federer":   PatternFill("solid", fgColor="375623"),
        "B — Moderate Federer": PatternFill("solid", fgColor="7B6200"),
        "C — Weak Federer":     PatternFill("solid", fgColor="833C00"),
        "D — Not Federer":      PatternFill("solid", fgColor="9C0006"),
    }
    score_fill = {
        "A": PatternFill("solid", fgColor="C6EFCE"),
        "B": PatternFill("solid", fgColor="FFEB9C"),
        "C": PatternFill("solid", fgColor="FFCC99"),
        "D": PatternFill("solid", fgColor="FFC7CE"),
    }

    ws.row_dimensions[1].height = 36
    for col_idx, cell in enumerate(ws[1], start=1):
        col_name = all_col_names[col_idx - 1] if col_idx - 1 < len(all_col_names) else ""
        cell.fill      = new_fill if col_name in NEW_COLS else orig_fill
        cell.font      = hdr_font
        cell.alignment = Alignment(horizontal="center", vertical="center", wrap_text=True)
        cell.border    = border

    for row in ws.iter_rows(min_row=2, max_row=ws.max_row):
        for cell in row:
            col_name = all_col_names[cell.column - 1] if cell.column - 1 < len(all_col_names) else ""
            cell.border    = border
            cell.alignment = Alignment(vertical="top", wrap_text=True)
            base_font      = Font(size=9, name="Arial")
            if col_name == "Verdict":
                fill = verdict_fill.get(str(cell.value))
                if fill: cell.fill = fill
                cell.font = Font(size=9, name="Arial", bold=True)
            elif col_name == "Score Band":
                fill = band_fill.get(str(cell.value))
                if fill: cell.fill = fill
                cell.font = Font(size=9, name="Arial", bold=True, color="FFFFFF")
            elif col_name == "Federer Score":
                try:
                    v    = int(float(str(cell.value)))
                    band = "A" if v >= 85 else "B" if v >= 60 else "C" if v >= 35 else "D"
                    cell.fill = score_fill[band]
                    cell.font = Font(size=9, name="Arial", bold=True)
                except Exception:
                    cell.font = base_font
            else:
                cell.font = base_font

    width_map = {
        "S.No.":6,"Company Name":24,"Address":32,"Website":24,
        "Segment":22,"What They Make":30,"Revenue Band":14,
        "Decision Maker":22,"DM Title":20,"DM Background":38,
        "C1 Manufacturer Score":15,"C1 Evidence":36,
        "C2 India Score":15,"C2 Evidence":36,
        "C3 Differentiation Score":15,"C3 Evidence":36,
        "C4 Tech DM Score":15,"C4 Evidence":36,
        "C5 Tailwind Score":15,"C5 Evidence":36,
        "C6 Growth Score":15,"C6 Evidence":36,
        "Federer Score":13,"Score Band":24,"Verdict":15,
        "Verdict Reasoning":42,"Personalization Hook":44,"Evidence Sources":42,
    }
    for col_idx, col_name in enumerate(all_col_names, start=1):
        ws.column_dimensions[get_column_letter(col_idx)].width = width_map.get(col_name, 18)

    ws.freeze_panes = "C2"
    wb.save(output_path)


# ── Main ──────────────────────────────────────────────────────────────────────

def main():
    print(f"\n{'='*62}")
    print(f"  Hyderabad Pharma Enrichment Tool  (v3)")
    print(f"  Input : {INPUT_FILE}")
    print(f"  Output: {OUTPUT_FILE}")
    print(f"{'='*62}\n")

    # Key validation
    if not GEMINI_API_KEY or GEMINI_API_KEY in ("PASTE_YOUR_AIza_KEY_HERE", ""):
        print("❌  GEMINI_API_KEY is not set!")
        print("   1. Go to: https://aistudio.google.com/app/apikey")
        print("   2. Click 'Create API key'")
        print("   3. Copy the key (starts with AIza...)")
        print("   4. Paste it into GEMINI_API_KEY at the top of this script")
        sys.exit(1)

    if not GEMINI_API_KEY.startswith("AIza"):
        print(f"⚠️  WARNING: Your key starts with '{GEMINI_API_KEY[:6]}...' — Gemini keys must start with 'AIza'")
        print("   This key will likely fail. Get a correct key at: https://aistudio.google.com/app/apikey\n")

    if not os.path.exists(INPUT_FILE):
        print(f"❌  '{INPUT_FILE}' not found.")
        print("   Upload the file to Colab first (drag it into the Files panel on the left)")
        sys.exit(1)

    print("Probing available Gemini models …")
    get_working_model()
    print()

    df = pd.read_excel(INPUT_FILE, header=1)
    df.columns = df.columns.str.strip()
    df = df.dropna(subset=["Company Name"]).reset_index(drop=True)
    df["Website"] = df["Website"].astype(str).str.strip()

    total = len(df)
    print(f"Loaded {total} companies.\n")

    enriched_rows = []
    for i, row in df.iterrows():
        name = row.get("Company Name", f"Row {i+1}")
        print(f"[{i+1:02d}/{total}] {name}")
        print(f"{'─'*55}")
        data = enrich_row(row)
        enriched_rows.append(data)
        print(f"    Done — Federer: {data.get('Federer Score','?')}  "
              f"Verdict: {data.get('Verdict','?')}\n")
        time.sleep(PAUSE)

    enriched_df   = pd.DataFrame(enriched_rows, columns=NEW_COLS)
    final_df      = pd.concat([df.reset_index(drop=True), enriched_df], axis=1)
    all_col_names = list(final_df.columns)

    final_df.to_excel(OUTPUT_FILE, index=False, engine="openpyxl")
    print("Applying formatting …")
    style_workbook(OUTPUT_FILE, len(df.columns), all_col_names)

    print(f"\n✅  Enrichment complete!")
    print(f"   Output saved to: {OUTPUT_FILE}")
    print(f"   Rows processed : {total}\n")


if __name__ == "__main__":
    main()